# GitHub Pages Configuration for Tondar VPN Update Page
title: "Tondar VPN Update"
description: "صفحه بروزرسانی اپلیکیشن Tondar VPN"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: fa
author: "Tondar VPN Team"

# Social and metadata
url: ""  # This will be set automatically by GitHub Pages
baseurl: "" # Leave empty for user/organization pages

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages

# Collections
collections:
  releases:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: "fa"

# Custom variables
vpn_name: "Tondar VPN"
current_version: "1.0.3"
release_date: "2024-01-01" 